# Generated by Django 3.2.6 on 2021-11-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211107_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvbuser',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
