# Generated by Django 3.2.6 on 2021-11-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_cvbuser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvbuser',
            name='cv_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
