# Generated by Django 3.2.6 on 2022-02-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_workexperienceentry_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperienceentry',
            name='title',
            field=models.CharField(default='hey', max_length=200),
            preserve_default=False,
        ),
    ]
